---
# ensure default dirs are removed
- name: "stat: ~/Documents"
  stat:
    path: "{{ansible_env.HOME}}/Documents"
  register: dox
#- name: "file:rm: ~/documents/"
#  file:
#    state: absent
#    name: "{{ansible_env.home}}/documents"
#  when: dox.stat.isdir
#  become: root
- name: "stat: ~/Pictures"
  stat:
    path: "{{ansible_env.HOME}}/Pictures"
  register: pix
#- name: "file:rm: ~/Pictures/"
#  file:
#    state: absent
#    name: "{{ansible_env.HOME}}/Pictures"
#  when: pix.stat.isdir
#  become: root

# link shared storage into home
# - name: "file:ln: ~/Documents"
#   file:
#     state: link
#     name: "{{ansible_env.HOME}}/Documents"
#     src: "{{share_dir}}/Documents"
#     force: yes
# - name: "file:ln: ~/Pictures"
#   file:
#     state: link
#     name: "{{ansible_env.HOME}}/Pictures"
#     src: "{{share_dir}}/Pictures"
- name: "file:ln: ~/src"
  file:
    state: link
    name: "{{ansible_env.HOME}}/src"
    src: "{{share_dir}}/src"
- name: "file:ln: ~/.bin"
  file:
    state: link
    name: "{{ansible_env.HOME}}/.bin"
    src: "{{share_dir}}/src/github.com/josephholsten/bin"
- name: "file:ln: ~/.dotfiles"
  file:
    state: link
    name: "{{ansible_env.HOME}}/.dotfiles"
    src: "{{share_dir}}/src/gitlab.com/josephholsten/dotfiles"
