---
# dev

# dev:plan9
# - osxfuse
# dev:plan9
# - freetype

# dev:plan9
# - git: repo=https://github.com/9fans/plan9port dest=/opt/plan9

# dev:go
# go_get: name=golang.org/x/tools/cmd/eg
# go_get: name=golang.org/x/tools/cmd/godoc
# go_get: name=golang.org/x/tools/cmd/goimports
# go_get: name=golang.org/x/tools/cmd/gorename
# go_get: name=golang.org/x/tools/cmd/oracle
# go_get: name=golang.org/x/tools/cmd/vet
# go_get: name=golang.org/x/review/git-review
# go_get: name=github.com/golang/lint/golint
#
# go_get: name=github.com/jstemmer/gotags
# go_get: name=github.com/kisielk/errcheck
# go_get: name=github.com/nsf/gocode
# go_get: name=code.google.com/p/rog-go/exp/cmd/godef
# go_get: name=github.com/mitchellh/gox
#
#
# good stuff:
# - code.google.com/p/rsc
# - code.google.com/p/rog-go
#
# go_get: name=code.google.com/p/rsc/arq/arqfs
# golint
# gox
# nolo-json
# terraform

