---
# Install
- homebrew_cask:
    name: hammerspoon

# Config
- name: First run
  osx_defaults:
    domain: org.hammerspoon.Hammerspoon
    key: SUHasLaunchedBefore
    type: bool
    value: true
- name: Disable Dock Icon
  osx_defaults:
    domain: org.hammerspoon.Hammerspoon
    key: MJShowDockIconKey
    type: bool
    value: false
