---

# - name: neovim tap
#   homebrew_tap:
#     name: homebrew/completions
#   with_items:
#   - homebrew/completions
#   - caskroom/cask
#   - caskroom/fonts
#   - josephholsten/josephholsten

- include: _pkg.yml
- include: _osx_defaults.yml
- include: _shared_storage.yml
- include: safari.yml
- include: mail.yml
- include: dev_common.yml
- include: dev_ruby.yml

- name: base tools
  homebrew:
    name: "{{item}}"
  with_items:
  # package managers
  - node    # required for npm
  - python3 # required for pip3
  - python  # osx ships with 2.7.6, which is insecure
  - go      # required for go get
  - mas     # mac app store
  # updated
  - bash  # osx default is 3.2.57
  - ctags # osx default is bsd
  - git   # osx ships with 2.3.2, which is ancient
  # improved
  - coreutils            # gnu tooling, almost entirely for realpath
  - fasd                 # improved cd(1)
  - ripgrep              # improved grep(1)
  - ssh-copy-id          # osx ssh is missing it
  - the_silver_searcher  # improved grep(1)
  - watch                # improved while true do; ... done
  - xz                   # improved compress/gzip
  - editorconfig         # improved modeline
  # events
  - fswatch      # file change events
  - sleepwatcher # wakeup events
  # stores
  - mackup       # dotfile store (deprecated in favor of stow)
  - stow         # dotfile store
  - pass         # password store
  - ghq          # rcs store
  - offline-imap # mail store sync
  - vdirsyncer   # card/cal store sync
  # api
  - exiftool       # image metadata cli
  - hub            # github cli
  - imagesnap      # laptop camera cli
  - jq             # json maniplation cli
  - pandoc         # text document convertion
  - lynx           # html to text
  - path-extractor # path extractor
  # ui
  - hig              # multi-rcs ui
  - nixpp            # shorthands posix fallbacks
  - bash-completion  # shell completions
  - fzf              # fuzzy item select
  - peco             # fuzzy item select
  - mutt             # maildir ui
  - khal             # vcal ui
  - khard            # vcard ui
  # dev
  - shellcheck # sh linter
  # - golint
  # - gofmt
  # - godef
  # - goimports
  # - gotags
  # - guru
  # - clib
  # - cscope
  # - ctags
  # - splint
  # - dash       # posix sh
  # - dsh # dancer's shell
  # - jo                   # json output
  # - ledger               # accounting store
  # - remind               # reminder store
  # - oath-toolkit         # otp generator
  # - speedread
  # - task                 # taskwarrior
  # - urlview              # extract urls from emails
  # - socat

  # installed packages
  # - htop
  # - hugo
  # - less
  # - mtr
  # - parallel
  # - pstree
  # - pwgen
  # - qrencode
  # - ruby
  # - ruby-install
  # - sqlite
  # - terminal-notifier
  # - tokei
  # - tree
  # - unar

- name: base
  homebrew_cask:
    name: "{{item}}"
  with_items:
  # stores
  - dropbox   # file store sync
  - 1password # password store
  - mylio     # photo store
  - keybase   # secure file store
  # - workflowy # outlining / external brain TODO: create cask
  # ui
  - hammerspoon # window manip ui
  - firefox     # browser
  # firefox plugins
  # - stylish
  # Based on these security recomentations:
  # https://vikingvpn.com/cybersecurity-wiki/browser-security/guide-hardening-mozilla-firefox-for-privacy-and-security
  # https://prism-break.org/en/subcategories/macos-web-browser-addons/
  # - disconnect
  # - https everywhere
  # - lightbeam
  # - privacy badger
  # - ublock origin
  # - umatrix
  # Not really
  # - noscript
  # - mailvelope
  # - better privacy
  # - cookie controller
  # - ghostery
  - gpgtools    # encryption ui
  - torbrowser # anonymous browser
  - iterm2 # terminal
  # misc
  - gemini # deduplication
  - keepingyouawake # prevent sleep events
  - marked
  # - caskroom/fonts/font-hasklig # ligatures # TODO: fix broken installation under ansible
  # - qlmarkdown
  # - docker
  # - graphviz
  # - arq
  # - flux
  # - quicksilver  # launcher
  # - franz       # chat ui
  # fallback
  - atom
  - google-chrome
  # testing
  - appcleaner
  - daisydisk
  - day-o
  - handbrake
  - prince
  - sabaki
  - skype
  - skype
  - zoomus
  - battle-net
  - discord
  - malwarebytes
  - slack


  # apps in app store:
  # - todoist

  # Apps to manually install:
  # - family-tree-maker

- name: urlscan
  pip:
    name: urlscan
    executable: /usr/local/bin/pip3

- name: ntfy
  pip:
    name: ntfy
    executable: /usr/local/bin/pip3


- name: dev:chef
  homebrew_cask:
    name: chefdk


- name: neovim tap
  homebrew_tap:
    name: neovim/neovim
- name: neovim
  homebrew:
    name: neovim/neovim/neovim

- name: nvim:plugins:update
  command: nvim -c PlugUpdate -c quit -c quit


# launcher {
# - flashlight https://github.com/w0lfschild/Flashlight
# - cerebro
# - dext https://github.com/vutran/dext
# - quicksilver
# - zazu
# }
