---
- include: _pkg.yml
- include: _shared_storage.yml
- include: _osx_defaults.yml

- include: base.yml
- include: nixpp.yml
- include: hig.yml

- include: personal.yml

- include: dev.yml
- include: dev_c.yml
- include: dev_chef.yml
- include: dev_go.yml
- include: dev_ruby.yml

- include: text.yml
- include: text_atom.yml
- include: text_emacs.yml
- include: text_vim.yml
