---

- name: personal
  homebrew:
    name: "{{item}}"
  with_items:
  # improved x
  - keybase
  # - mobile-shell # ssh
  # - par # fmt
  # - multitail
  # niceties
  # - tmux # term muxer
  # - md5sha1sum
  # - reattach-to-user-namespace # hack to make tmux play with mac
  # networking
  # - dsh
  # - ipcalc
  # mail
  # - notmuch
  # security
  # - fortune
  # - gnu-typist # typing lessons
  # - imagemagick # image manip
  # - ledger # accounting
  # - nethack # the game
  # - remind # calendaring
  # self-stalking
  # - imagesnap # laptop camera cli # FIXME: broken on osx 10.12
  # - nolo # meter -> sink adopters
  # - sleepwatcher # actions on wakeup
  # - selfspy
  # - andrewning / sortphotos
  # - nwinter/telepath-logger
  # botrus dev
  # - bsdiff # binary diff
  # - perceptualdiff # image cmp
  # - xdelta # binary diff
  # - tag # osx file tag manip
  # - influxdb # timeseriesdb
  ### Just playing with these things
  - miller
  - commonmark
  - slackcat

- name: personal
  homebrew_cask:
    name: "{{item}}"
  with_items:
  - steam # gaming
  # - adium              # instant messaging
  # - cyberduck          # foss sftp
  # - flux
  # - keepassx           # foss password safe
  # - transmit           # sftp
  # - transmission       # bittorent
  # - panic-unison       # usenet
  # - torbrowser         # tor + web browser
  # - calibre            # ebook mgmt
  # - papers             # biblio mgmt
  # - bitcoin-core       # money access
  # - electric-sheep     # the screensaver
  # - geektool           # desktop viz
  # - daisydisk          # fs usage viz
  # - musicbrainz-picard # music tagging
  # - tuneup             # music tagging
 
# - gem: name={{ item }}
#   with_items:

# - pip: name={{ item }}
#   with_items:

# - go_get: name=github.com/xordataexchange/crypt/bin/crypt
